[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
force = true
disable = false
port = 8181
interface = "127.0.0.1"
[websockets]
disable = false
port = 8547
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00D02CFe33C8Db1b70F64d8B18e13839B6E25262"
reseal_on_txs = "none"
