[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
force = true
disable = false
port = 8180
interface = "127.0.0.1"
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00bD49d7Fa557d7515F7E07fBcEa353d13dC1159"
reseal_on_txs = "none"

